### ISSUE TITLE
Form Facade alias

### ISSUE THREAD

**Issue by ricardovigatti** [netojose/laravel-bootstrap-4-forms#40]
Laravel version: 5.6

After being installed, your package's alias is overriding my Form Collective package. I've tried to inform an alias but without effect.

```
// config/app.php
/*
 * Package Aliases...
*/
'Bootstrap4Form' => NetoJose\Bootstrap4Forms\Bootstrap4FormsFacade::class,
'Form' => Collective\Html\FormFacade::class,
```

Trying to use {!! Form:: !!} is reaching your package instead of Collective.

How can i solve?

**Comment by netojose** [comment]
Hi @ricardovigatti , First of all, sorry for delay in response.
When I used de auto discovery package from Laravel, and I decided use this alias, I think this could be a problem. But... I think make no sense use the both packages in a same project, because both does the same thing. I don't know how set the Alias name. But... according with official documentation, you can disable auto discovery for individual packages, so you can do this:

```
"extra": {
    "laravel": {
        "dont-discover": [
            "netojose/laravel-bootstrap-4-forms"
        ]
    }
},
```

After this, you can make a manual alias and choose your alias name.
